### ISSUE TITLE
Openwrt的Docker上安装时 网站开放端口会有冲突么

### ISSUE THREAD

**Issue by fallingupyoung** [Cyberbolt/baota#3]
访问端口没问题 是 8888，但是网站端口默认是80，跟Openwrt一样，怎么避免冲突？

**Comment by Cyberbolt** [comment]
将 openwrt 默认端口改为非80端口，再用Nginx的80或443端口反向代理修改的 openwrt 端口

**Comment by Cyberbolt** [comment]
否则就只能一个应用使用80端口
