### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by juzijun233** [Cyberbolt/baota#9]
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'.*\xef\xbc\x9a')
正在设置面板端口
正在设置面板用户名
Traceback (most recent call last):
  File "script.py", line 98, in <module>
    main()
  File "script.py", line 82, in main
    bt_init(data['port'], data['username'], data['password'])
  File "script.py", line 42, in bt_init
    child.expect('.*：'.encode('utf-8'))
  File "/usr/local/lib/python3.7/dist-packages/pexpect/spawnbase.py", line 344, in expect
    timeout, searchwindowsize, async_)
  File "/usr/local/lib/python3.7/dist-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 179, in expect_loop
    return self.eof(e)
  File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 122, in eof
    raise exc
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7fc792f38d30>
command: /usr/bin/bt
args: ['/usr/bin/bt']
buffer (last 100 chars): b''
before (last 100 chars): b't.pl: No such file or directory\r\n/usr/bin/bt: line 339: /usr/bin/python: No such file or directory\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: 127
flag_eof: True
pid: 22
child_fd: 6
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'.*\xef\xbc\x9a')
正在设置面板端口
正在设置面板用户名
Traceback (most recent call last):
  File "script.py", line 98, in <module>
    main()
  File "script.py", line 82, in main
    bt_init(data['port'], data['username'], data['password'])
  File "script.py", line 42, in bt_init
    child.expect('.*：'.encode('utf-8'))
  File "/usr/local/lib/python3.7/dist-packages/pexpect/spawnbase.py", line 344, in expect
    timeout, searchwindowsize, async_)
  File "/usr/local/lib/python3.7/dist-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 179, in expect_loop
    return self.eof(e)
  File "/usr/local/lib/python3.7/dist-packages/pexpect/expect.py", line 122, in eof
    raise exc
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7f4903fc9c88>
command: /usr/bin/bt
args: ['/usr/bin/bt']
buffer (last 100 chars): b''
before (last 100 chars): b't.pl: No such file or directory\r\n/usr/bin/bt: line 339: /usr/bin/python: No such file or directory\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: 127
flag_eof: True
pid: 22
child_fd: 6
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'.*\xef\xbc\x9a')

命令
```
docker run -itd --net=host --restart=always -v /srv/dev-disk-by-uuid-89fd10bb-5192-4cfb-beac-f547395b3209/bt_data:/www \
--name bt-panel cyberbolt/baota \
-port 8888 -username homeserver -password <*****>
```

**Comment by Cyberbolt** [comment]
没看出什么问题，你可以用默认命令试试吗？
`docker run -itd --net=host --restart=always \
--name baota cyberbolt/baota \
-port 8888 -username cyberbolt -password abc123456`

**Comment by magellan-99** [comment]
我已经找到原因，请修改一下你的“方案二（生产环境部署）”的部署语句为：
docker run -itd -v /www/www:/www --net=host --restart=always \
--name baota cyberbolt/baota \
-port 8888 -username cyberbolt -password abc123456

**Comment by magellan-99** [comment]
> 没看出什么问题，你可以用默认命令试试吗？ `docker run -itd --net=host --restart=always \ --name baota cyberbolt/baota \ -port 8888 -username cyberbolt -password abc123456`

在你的个人网站上提问，也没有人回答。没办法上github来了。有个问题请教一下：如何让容器中的网站能访问宿主机的卷或者目录结构？比如我在docker的容器中安装了一个可道云，宿主机上有一个更大的卷，能存放更多的文件，此时如何让容器能访问它呢？

**Comment by Cyberbolt** [comment]
> 我已经找到原因，请修改一下你的“方案二（生产环境部署）”的部署语句为： docker run -itd -v /www/www:/www --net=host --restart=always --name baota cyberbolt/baota -port 8888 -username cyberbolt -password abc123456

最近比较忙，抱歉。应该是你的系统目录已经有 /www 了，如果是纯净的系统，用方案二的命令应该没问题。
